name: asyou_app
description: A DAO client with substrate.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 多语言
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  # rust 链桥
  flutter_rust_bridge: 1.71.1
  # 动画库
  lottie: ^2.2.0
  # 组件动画库
  entry: ^0.0.6
  # 英文扩展包
  english_words: ^4.0.0
  # 表情包
  flutter_emoji: ^2.4.0
  # 语法扩展
  expandable: ^5.0.1
  # 路由
  go_router: ^6.0.9
  # 主题
  themed: ^4.0.0
  # 桌面客户端样式
  window_manager: ^0.3.0
  # nosql 数据库
  objectbox: ^1.7.2
  objectbox_flutter_libs: ^1.7.2
  # 全局状态树
  provider: ^6.0.4
  # 表情包
  emoji_picker_flutter: ^1.5.2
  # c库调用
  ffi: ^2.0.1
  # 状态管理
  freezed_annotation: ^2.2.0
  # json
  json_annotation: ^4.7.0
  # 多选框
  chips_choice: ^3.0.0
  # matrix 连接库
  matrix: ^0.18.0
  matrix_link_text: ^1.0.2
  flutter_matrix_html: ^1.1.0
  # 加载框
  future_loading_dialog: ^0.2.3
  # 日期格式化插件
  date_format: ^2.0.7
  # easy_localization: ^3.0.1
  path_provider: ^2.0.13
  # 音频
  just_audio: ^0.9.31
  # 弹窗
  adaptive_dialog: ^1.8.2
  # 缩略图
  flutter_blurhash: ^0.7.0
  # 视频播放器
  video_player: ^2.6.0
  universal_html: ^2.2.1

  chewie: ^1.4.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  punycode: ^1.0.0
  url_launcher: ^6.1.10
  collection: ^1.17.0
  flutter_secure_storage: ^8.0.0
  file_picker_cross: ^4.6.0
  share_plus: ^4.0.10+1
  image_picker: ^0.8.7
  tab_indicator_styler: ^2.0.0
  desktop_notifications: ^0.6.3
  desktop_lifecycle: ^0.1.0
  bot_toast: ^4.0.3
  badges: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  objectbox_generator: any
  freezed: ^2.2.0
  build_runner: ^2.2.0
  ffigen: ^7.2.6
  json_serializable: ^6.5.4

dependency_overrides:
  # c库调用
  ffi: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/l10n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
