name: dtim
description: A DAO client with substrate.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 多语言
  flutter_localizations:
    sdk: flutter
  # 国际化
  intl: any
  cupertino_icons: ^1.0.2
  # rust 链桥
  flutter_rust_bridge: ^1.82.6
  # 动画库
  lottie: ^2.2.0
  # 组件动画库
  # entry: ^0.0.6
  # 英文扩展包
  english_words: ^4.0.0
  # 表情包
  flutter_emoji: ^2.4.0
  # 语法扩展
  expandable: ^5.0.1
  # 路由
  auto_route: ^7.7.1
  # 主题
  adaptive_theme: ^3.2.0
  # 桌面客户端样式
  window_manager: ^0.3.0
  # nosql 数据库
  hive: ^2.2.3
  # 全局状态树
  flutter_bloc: ^8.1.2
  # 表情包
  emoji_picker_flutter: ^1.5.2
  # 状态管理
  freezed_annotation: ^2.2.0
  # json
  json_annotation: ^4.8.1
  # 多选框
  chips_choice: ^3.0.0
  # matrix 连接库
  matrix: ^0.25.8
  matrix_link_text: ^2.0.0
  # 日期格式化插件
  date_format: ^2.0.7
  # easy_localization: ^3.0.1
  path_provider: ^2.0.14
  # 音频
  audioplayers: ^5.2.1
  # 弹窗
  adaptive_dialog: ^1.9.0-0
  # 缩略图
  flutter_blurhash: ^0.8.2
  # 视频播放器
  video_player: ^2.7.0
  # html
  universal_html: ^2.2.1
  # 文字动画
  animated_text_kit: ^4.2.2
  # svg
  flutter_svg: ^2.0.5
  # webrtc
  flutter_webrtc: ^0.9.35
  webrtc_interface: ^1.1.0
  # 托盘管理
  tray_manager: ^0.2.0
  # 视频播放
  chewie: ^1.4.1
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  punycode: ^1.0.0
  # 打开url
  url_launcher: ^6.1.10
  # 实用程序函数
  collection: ^1.17.1
  # 隐私储存
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.0
  # tab 样式
  tab_indicator_styler: ^2.0.0
  # 桌面通知
  desktop_notifications: ^0.6.3
  # 桌面生命周期
  desktop_lifecycle: ^0.1.0
  # toast弹窗
  bot_toast: ^4.0.3
  # 右上角数字
  badges: ^3.0.2
  # 加密
  flutter_olm: ^1.2.0
  flutter_openssl_crypto: ^0.3.0
  # fl_chart: ^0.63.0
  video_compress: ^3.1.2
  # 录音
  record: ^5.0.1
  # 函数防抖
  easy_debounce: ^2.0.3
  # 文件选择
  file_picker: ^6.0.0
  # 后台任务
  flutter_foreground_task: ^6.0.0+1
  # 储存
  hive_flutter: ^1.1.0
  # 设备信息
  device_info_plus: ^9.0.2
  polkadart: ^0.3.2
  # polkadart_keyring: ^0.2.1
  # substrate_bip39: ^0.2.0
  convert: ^3.1.1
  provider: ^6.1.1
  polkadart_keyring: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^7.0.0
  hive_generator: ^2.0.0
  freezed: ^2.4.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  polkadart_cli: ^0.3.2
  # dart_code_metrics: ^5.7.3
  # iconfont_convert: ^1.0.0

dependency_overrides:
  # http: ^0.13.5
  collection: ^1.18.0

polkadart:
  output_dir: lib/chain
  chains:
    wetee_gen: ws://127.0.0.1:9944

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/l10n/
    - assets/images/
    - assets/icons/
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

