# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: lib_build

on:
  push:
    branches: [ "main" ]
    # paths:
    #   - 'rust_wraper'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cd rust_wraper && cargo build --release 
          
