name: Windows CI

on: workflow_dispatch

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2 # v3.5.2
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v2.10.0
    # Build the app for Windows.  
      - run: flutter build windows --release
    
      - name: Import GPG key  
        run: |
            echo gpg --import --no-tty --batch --yes packages.microsoft.gpg

      - name: Sign Windows artifact 
        run: |
            gpg --detach-sign "*.zip"
        working-directory: ./build/windows/runner/Release

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
            name: Windows
            path: ./build/windows/runner/Release

      - name: Upload Windows signature
        uses: actions/upload-artifact@v2
        with:
            name: Windows_signature
            path: ./build/windows/runner/Release/*.zip.sig